version: "3"

services:
  mysql: # MySQL container.
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: 1q2w3e4r5t
    volumes:
      - semaphore-mysql:/var/lib/mysql

  semaphore: # Semaphore container.
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "QfWtJhFYtIcAOFDbbZjpk9hFMobxY0WZf4o1PKnRQKI="
      SEMAPHORE_ADMIN: osadmin
      SEMAPHORE_ADMIN_EMAIL: osadmin@semaphore.local
      SEMAPHORE_ADMIN_NAME: osadmin
      SEMAPHORE_ADMIN_PASSWORD: QJOCWHI=
      SEMAPHORE_DB: semaphore
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: 1q2w3e4r5t
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_LDAP_ACTIVATED: "no"
      ANSIBLE_HOST_KEY_CHECKING: "False"

volumes:
  semaphore-mysql:
